name: Close Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    if: github.repository == 'OWNER/REPO'
    permissions:
      issues: write
    uses: OWNER/workflows/.github/workflows/stale-issues.yml@v1
    secrets: inherit
